services:
  # The "Traffic Cop" - Handles all incoming web requests
  nginx:
    image: nginx:alpine
    container_name: aws-practice-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:16-alpine
    container_name: aws-practice-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT_EXPOSE:-5432}:5432" # Maps 5432 only if needed
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: aws-practice-backend
    environment:
      PORT: ${BACKEND_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: aws-practice-frontend
    depends_on:
      - backend

volumes:
  db_data: