services:
  db:
    image: postgres:16-alpine
    container_name: aws-practice-db
    environment:
      POSTGRES_DB: usersdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build:
      context: ./backend
    container_name: aws-practice-backend
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: usersdb
    depends_on:
      - db
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: aws-practice-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  db_data:
